"""
Emit an OpenSCAD model of the lamp frame (vertices + edges) with the
rhombicosidodecahedron coordinates baked in.

    lamp_frame.scad   - open in OpenSCAD and hit F5 (preview) / F6 (render)

Struts = edges (rounded cylinders), nodes = spheres at the 60 vertices.
Geometry is parametric on DIAMETER / strut & node sizes at the top of the file.
"""

import numpy as np
import geometry


def fmt_vec(v):
    return "[%.4f, %.4f, %.4f]" % (v[0], v[1], v[2])


def main(diameter=200.0):
    V, F, E = geometry.build()           # unit circumsphere
    V = V * (diameter / 2.0)             # scale to requested diameter (mm)

    verts = ",\n    ".join(fmt_vec(v) for v in V)
    edges = ",\n    ".join("[%d, %d]" % (i, j) for i, j in E)

    scad = f"""// Ssymmank lamp frame -- rhombicosidodecahedron (vertices + edges)
// 60 vertices, 120 edges, 62 faces (12 pentagons, 30 squares, 20 triangles).
// Auto-generated by make_scad.py -- edit parameters below, then F5/F6.

DIAMETER   = {diameter:.1f};   // overall lamp diameter (mm)
STRUT_R    = 1.6;     // strut (edge) radius (mm)
NODE_R     = 3.2;     // node (vertex) sphere radius (mm)
$fn        = 24;      // smoothness

VERTS = [
    {verts}
];

EDGES = [
    {edges}
];

module strut(a, b) {{
    // rounded strut between two points via hull of two spheres
    hull() {{
        translate(a) sphere(r = STRUT_R);
        translate(b) sphere(r = STRUT_R);
    }}
}}

module frame() {{
    color("WhiteSmoke") {{
        for (e = EDGES) strut(VERTS[e[0]], VERTS[e[1]]);
        for (v = VERTS) translate(v) sphere(r = NODE_R);
    }}
}}

frame();
"""
    with open("lamp_frame.scad", "w") as fh:
        fh.write(scad)
    print(f"saved lamp_frame.scad  ({len(V)} vertices, {len(E)} edges, diameter {diameter:.0f}mm)")


if __name__ == "__main__":
    main()
