"""Regenerate models/assembly/assembly.scad + _overlap_check.scad from the solver.

The shingled layout that gives ZERO mushroom-mushroom intersection AND ZERO light
leak (both measured on the real solids). Importing `orient` runs the 5-colouring
and renders the 5 shell-variant mushrooms; this script then bakes the placement
matrices (shell radius + per-mushroom azimuth from theta_d26.json) into the .scad.

Run:  python3 src/assembly/shingle_solver/build.py
Requires OpenSCAD (set $OPENSCAD if not at the macOS default) + numpy/scipy.
"""
import json, math
from pathlib import Path
import numpy as np
from scipy.spatial import cKDTree
import orient, color3, analyze                       # noqa: import side effects
from core.transforms import _fmt_matrix

REPO = Path(__file__).resolve().parents[3]
ASM = REPO / "models" / "assembly"
LAMP_SCALE = 1.3797       # 435mm base dia -> 600mm lamp
MUSH_ALPHA = 0.7

theta = json.load(open(Path(__file__).parent / "theta_d26.json"))
col, STEMS, SOCKS = orient.col, orient.STEMS, orient.SOCKS

entries = []
for idx, ((kind, pt, top), c) in enumerate(zip(SOCKS, col)):
    M = orient.place_az(pt, top, STEMS[c], theta[idx])
    entries.append((M, STEMS[c]))
block = "[\n" + ",\n".join("    [%s, %.2f]" % (_fmt_matrix(M), sl) for M, sl in entries) + "\n]"

assembly = f"""// Ssymmank assembly -- full frame + 72 shingled mushrooms.
// SOLVED layout: zero mushroom-mushroom intersections AND zero light leak,
// verified on the real solids with OpenSCAD intersection() (see _overlap_check.scad).
// Generated by src/assembly/shingle_solver/build.py -- do not hand-edit the MUSH array.
//
//  * caps curved ~concentric with the lamp centre (CURVE_RELAX=2.3) -> radially thin
//  * 5 radial SHELLS (stems 70/84/98/112/126) by a 5-colouring of the cap-overlap
//    graph -> touching caps differ in shell, shingle (overlap angularly, clear radially)
//  * DISH_DEPTH=26 funnel clears the next-inner shell's caps
//  * 5 mushrooms spun about their radial axis so stretched arms reach into gaps
//  * stem tips all seat at the same bore floor -> frame UNCHANGED

use <../mushrooms/mushroom_simple.scad>;
include <../frame/stars_assembly.scad>   // the real (kinked star-decomposition) frame
SHOW_FRAME = false;

MUSH_SCALE = {orient.SCALE};    // cap size (coverage); shells keep mushrooms apart
LAMP_SCALE = {LAMP_SCALE};  // base model is 435mm dia (caps included) -> x{LAMP_SCALE} = 600mm lamp

// each entry: [ 4x4 placement (shell radius + azimuth baked in), stem_length ]
MUSH = {block};

MUSH_ALPHA = {MUSH_ALPHA};
scale(LAMP_SCALE) {{
    frame();   // kinked star-decomposition frame (from stars_assembly.scad)
    color("Cornsilk", MUSH_ALPHA)
        union()
            for (e = MUSH) multmatrix(e[0]) scale(MUSH_SCALE) mushroom(e[1], paint = false);
}}
"""
(ASM / "assembly.scad").write_text(assembly)

# overlap checker: close pairs (<10mm surface) from the solver's neighbour graph
pairs = sorted({tuple(sorted((a, b))) for a in range(len(SOCKS)) for b in orient.NB[a]})
pj = "[\n" + ",\n".join("    [%d, %d]" % (a, b) for a, b in pairs) + "\n]"
mush_arr = block
check = f"""// OVERLAP CHECK for assembly.scad -- renders ONLY the 3D intersection of each
// close mushroom pair. Red / non-empty STL = real physical intersection;
// "top level object is empty" / 0 facets = clean. Generated by build.py.
use <../mushrooms/mushroom_simple.scad>;
MUSH_SCALE = {orient.SCALE};
MUSH = {mush_arr};
PAIRS = {pj};
module one(i){{ multmatrix(MUSH[i][0]) scale(MUSH_SCALE) mushroom(MUSH[i][1], paint=false); }}
color("red") for (p = PAIRS) intersection(){{ one(p[0]); one(p[1]); }}
"""
(ASM / "_overlap_check.scad").write_text(check)
print(f"wrote {ASM/'assembly.scad'} and _overlap_check.scad ({len(entries)} mushrooms, {len(pairs)} check pairs)")
