// Ssymmank lamp -- STAR TILE (one of 12, all congruent).
// Hub socket + 5 spokes + 5 corner sockets + 5 boundary bars + 10 connector
// mortises, fused as one printable pentagonal wheel.  Hub at origin, +Z out.
// Auto-generated by build_star.py.

DIAMETER = 200.0;
EDGE_LEN = 44.7838;          // every edge/connector is this long (Archimedean)

EDGE_H = 10; EDGE_T = 1.0;          // bar height (radial) x thickness (1 mm)
STEM_TIP_R = 4; FIT_CLR = 0.35; SOCKET_WALL = 1.0;
SOCKET_H = EDGE_H; SOCKET_DEPTH = SOCKET_H - 1;
$fn = 32;
BORE_R_TIP = STEM_TIP_R + FIT_CLR;
BORE_R_MOUTH = STEM_TIP_R + FIT_CLR + 1.0;
NODE_R = 6.35;

// ---- keyed joint -----------------------------------------------------------
KEY_T = 1.0; KEY_H = 6.0; KEY_DEPTH = 6.0;
BACK = 1.0; NECK = 1.5; KEY_CLR = 0.50;   // Tough PLA, UM3: ~0.25mm/face (was 0.30, too tight)

// ---- edge kink -------------------------------------------------------------
// Every edge bends at its middle so each half leaves its vertex perpendicular to
// the socket axis (tangent to the sphere). The kink point M is where the sphere's
// tangent lines at the two vertices meet, a few mm proud of the chord.
RAD     = DIAMETER / 2;
HALF    = EDGE_LEN / 2;                       // half a chord
MIDR    = sqrt(RAD * RAD - HALF * HALF);      // radius of the chord midpoint
KINK_H  = HALF * HALF / MIDR;                 // outward rise of M above that mid
ARM_LEN = sqrt(HALF * HALF + KINK_H * KINK_H);// vertex -> M, straight
PHI     = atan2(KINK_H, HALF);                // tangent angle above the chord (deg)
GAP_OFF = NODE_R + BACK;                      // vertex -> mortise mouth, along the arm

module edge_bar() cube([1, EDGE_T, EDGE_H], center = true);   // x scaled by matrix

// A node is built in two halves so the bore can be subtracted from the WHOLE
// tile last (after the bars union on) -- otherwise the bars, which run the full
// edge length, drive through the node centre and refill the socket bore.
module node_solid() {
    // tapered to follow the conical bore, so the wall stays ~1 mm all the way to
    // the narrow (back) end -- the inner end is a thin open ring, not a thick floor.
    translate([0, 0, -SOCKET_H / 2])
        cylinder(h = SOCKET_H, r1 = BORE_R_TIP + SOCKET_WALL, r2 = NODE_R);
}
module bore() {
    // conical bore matched to the tapered stem ...
    translate([0, 0, -SOCKET_H / 2 + SOCKET_H - SOCKET_DEPTH + 0.5])
        cylinder(h = SOCKET_DEPTH + 0.5, r1 = BORE_R_TIP, r2 = BORE_R_MOUTH);
    // ... open the inner end straight through (no back/floor): a tip-radius
    // cylinder punching past the node bottom, so the node is an open tube.
    translate([0, 0, -SOCKET_H / 2 - 1])
        cylinder(h = SOCKET_H - SOCKET_DEPTH + 1.5, r = BORE_R_TIP);
    // ... then a straight clearance column continuing OUT past the fin height,
    // so no leaning bar (its tall axis is radial at the edge mid, not at the
    // vertex) can overhang the socket opening. Radius = mouth, so the 1 mm node
    // wall survives.
    translate([0, 0, SOCKET_H / 2 - 1.5])
        cylinder(h = EDGE_H + 2, r = BORE_R_MOUTH);
}

// mortise boss at a corner: tilted UP by PHI so it aims along the kinked edge's
// tangent (perpendicular to the socket), grows into the gap so it never breaches
// the bore. Tenon plugs in from the gap face.
module receiver() {
    bw = KEY_T + 2 * SOCKET_WALL; bh = KEY_H + 2 * SOCKET_WALL;
    x0 = NODE_R - NECK;  xlen = NECK + BACK + KEY_DEPTH;
    rotate([0, -PHI, 0])
    difference() {
        translate([x0, -bw / 2, -bh / 2]) cube([xlen, bw, bh]);
        translate([NODE_R + BACK, -(KEY_T + KEY_CLR) / 2, -(KEY_H + KEY_CLR) / 2])
            cube([KEY_DEPTH + 0.2, KEY_T + KEY_CLR, KEY_H + KEY_CLR]);
    }
}

// one connector: a shallow V (kink at the centre, apex M raised by KINK_H), with a
// keyed tenon near each vertex that plugs into that corner's tilted boss. Planar
// (lies in the XZ plane), so it prints flat. All 60 are identical.
module conn_half() {
    fin0 = GAP_OFF + KEY_DEPTH;                 // where the visible fin starts
    translate([-HALF, 0, 0]) rotate([0, -PHI, 0]) {
        translate([GAP_OFF, -KEY_T / 2, -KEY_H / 2])
            cube([KEY_DEPTH, KEY_T, KEY_H]);     // tenon (into the tilted boss)
        translate([fin0, -EDGE_T / 2, -EDGE_H / 2])
            cube([ARM_LEN - fin0, EDGE_T, EDGE_H]);   // arm up to the kink at M
    }
}
// the M-end cross-section of one arm; hull of both miters the centre kink so the
// two arms meet without a V-notch (same fix as the star bars' kink_welds).
module conn_tip() {
    translate([-HALF, 0, 0]) rotate([0, -PHI, 0])
        translate([ARM_LEN - 0.01, -EDGE_T / 2, -EDGE_H / 2])
            cube([0.01, EDGE_T, EDGE_H]);
}
module connector() {
    conn_half(); mirror([1, 0, 0]) conn_half();
    hull() { conn_tip(); mirror([1, 0, 0]) conn_tip(); }   // miter the kink
}

STAR_NODE_M = [
        [[-0.58779, -0.80902, -0.00000, 0.00000], [0.80902, -0.58779, 0.00000, 0.00000], [0.00000, 0.00000, 1.00000, -0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.33552, -0.93465, 0.11772, 11.77212], [0.86180, -0.35500, -0.36231, -36.23085], [0.38042, -0.02011, 0.92459, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.47434, -0.79365, 0.38095, 38.09537], [0.85837, -0.51303, 0.00000, 0.00000], [0.19544, 0.32700, 0.92459, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.66978, -0.73317, 0.11772, 11.77212], [0.71638, -0.59627, 0.36231, 36.23085], [-0.19544, 0.32700, 0.92459, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.71594, -0.62645, -0.30820, -30.81980], [0.58541, -0.77920, 0.22392, 22.39190], [-0.38042, -0.02011, 0.92459, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.58779, -0.74801, -0.30820, -30.81980], [0.80902, -0.54346, -0.22392, -22.39190], [0.00000, -0.38095, 0.92459, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]]
];
STAR_BAR_M = [
        [[6.11668, 0.95106, 0.00000, 3.05834], [-18.82519, 0.30902, -0.00000, -9.41260], [-0.00000, 0.00000, 1.00000, -0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[5.65544, 0.95106, 0.11772, 8.94440], [-17.40566, 0.30902, -0.36231, -27.52802], [-7.54059, 0.00000, 0.92459, -3.77029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[19.79398, 0.00000, -0.00000, 9.89699], [0.00000, 1.00000, 0.00000, 0.00000], [0.00000, 0.00000, 1.00000, 0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[18.30139, 0.00000, 0.38095, 28.94467], [-0.00000, 1.00000, 0.00000, -0.00000], [-7.54059, -0.00000, 0.92459, -3.77029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[6.11668, -0.95106, -0.00000, 3.05834], [18.82519, 0.30902, -0.00000, 9.41260], [0.00000, 0.00000, 1.00000, 0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[5.65544, -0.95106, 0.11772, 8.94440], [17.40566, 0.30902, 0.36231, 27.52802], [-7.54059, 0.00000, 0.92459, -3.77029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-16.01366, -0.58779, -0.00000, -8.00683], [11.63461, -0.80902, 0.00000, 5.81730], [-0.00000, -0.00000, 1.00000, -0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-14.80614, -0.58779, -0.30820, -23.41673], [10.75729, -0.80902, 0.22392, 17.01325], [-7.54059, -0.00000, 0.92459, -3.77029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-16.01366, 0.58779, -0.00000, -8.00683], [-11.63461, -0.80902, -0.00000, -5.81730], [-0.00000, 0.00000, 1.00000, -0.00000], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-14.80614, 0.58779, -0.30820, -23.41673], [-10.75729, -0.80902, -0.22392, -17.01325], [-7.54059, 0.00000, 0.92459, -3.77029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[14.47779, -0.76750, 0.11772, 19.01101], [17.15918, 0.55762, -0.36231, -27.65126], [4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[11.84546, -0.76750, 0.38095, 32.17264], [19.07167, 0.55762, 0.00000, -9.53584], [-4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-11.84546, -0.76750, 0.38095, 32.17264], [19.07167, -0.55762, 0.00000, 9.53584], [4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-14.47779, -0.76750, 0.11772, 19.01101], [17.15918, -0.55762, 0.36231, 27.65126], [-4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-21.79869, 0.29316, 0.11772, 0.87277], [-5.37223, -0.90225, 0.36231, 33.54473], [4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-20.79323, 0.29316, -0.30820, -20.42319], [-8.46672, -0.90225, 0.22392, 26.62526], [-4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-1.62687, 0.94868, -0.30820, -31.63324], [-22.39190, 0.00000, 0.22392, 11.19595], [4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[1.62687, 0.94868, -0.30820, -31.63324], [-22.39190, 0.00000, -0.22392, -11.19595], [-4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[20.79323, 0.29316, -0.30820, -20.42319], [-8.46672, 0.90225, -0.22392, -26.62526], [4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[21.79869, 0.29316, 0.11772, 0.87277], [-5.37223, 0.90225, -0.36231, -33.54473], [-4.88060, 0.31623, 0.92459, -5.10029], [0.00000, 0.00000, 0.00000, 1.00000]]
];
STAR_RECV_M = [
        [[0.68819, 0.66978, 0.27890, 11.77212], [-0.50000, 0.71638, -0.48662, -36.23085], [-0.52573, 0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.26287, 0.96294, 0.06039, 11.77212], [-0.80902, -0.18587, -0.55762, -36.23085], [-0.52573, -0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[0.68819, 0.47434, 0.54899, 38.09537], [-0.50000, 0.85837, -0.11488, 0.00000], [-0.52573, -0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.26287, 0.88829, -0.37662, -30.81980], [-0.80902, -0.41563, -0.41563, -22.39190], [-0.52573, 0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[0.68819, -0.47434, 0.54899, 38.09537], [0.50000, 0.85837, 0.11488, 0.00000], [-0.52573, 0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.85065, 0.12079, -0.51167, -30.81980], [0.00000, -0.97325, -0.22975, -22.39190], [-0.52573, -0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[0.68819, -0.66978, 0.27890, 11.77212], [0.50000, 0.71638, 0.48662, 36.23085], [-0.52573, -0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.26287, -0.96294, 0.06039, 11.77212], [0.80902, -0.18587, 0.55762, 36.23085], [-0.52573, 0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.85065, -0.12079, -0.51167, -30.81980], [0.00000, -0.97325, 0.22975, 22.39190], [-0.52573, 0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]],
        [[-0.26287, -0.88829, -0.37662, -30.81980], [0.80902, -0.41563, 0.41563, 22.39190], [-0.52573, -0.19544, 0.82790, -7.54059], [0.00000, 0.00000, 0.00000, 1.00000]]
];
// Each edge is two half-fins (STAR_BAR_M[2i] = a->M, STAR_BAR_M[2i+1] = M->b)
// meeting at the kink M. Their flat faces meet at an angle and leave a V-notch,
// so miter the kink: hull the two end cross-sections at M to fill the wedge.
module kink_welds() {
    for (i = [0 : len(STAR_BAR_M) / 2 - 1])
        hull() {
            multmatrix(STAR_BAR_M[2 * i])     translate([ 0.5, 0, 0])
                cube([0.001, EDGE_T, EDGE_H], center = true);
            multmatrix(STAR_BAR_M[2 * i + 1]) translate([-0.5, 0, 0])
                cube([0.001, EDGE_T, EDGE_H], center = true);
        }
}

module star() {
    difference() {
        union() {
            for (m = STAR_BAR_M)  multmatrix(m) edge_bar();
            kink_welds();                                 // miter each kink
            for (m = STAR_NODE_M) multmatrix(m) node_solid();
            for (m = STAR_RECV_M) multmatrix(m) receiver();
        }
        for (m = STAR_NODE_M) multmatrix(m) bore();   // clear every socket last
    }
}

// star.scad doubles as the shared library: every other frame model `include`s it
// for the params, modules and STAR_*_M data, then sets SHOW_STAR=false so this
// lone tile isn't drawn. Any edit here (e.g. kink_welds) propagates to all of them.
SHOW_STAR = true;
if (SHOW_STAR) star();   // hub at origin, sockets up; each edge kinks out perpendicular
