"""
Emit an OpenSCAD assembly: the frame plus mushrooms on one pentagon.

    models/assembly_pentagon.scad

  * the pentagon-CENTRE socket gets an XL mushroom,
  * the 5 corner sockets get, CLOCKWISE from the top corner (as seen from
    outside the lamp): small, medium, large, medium, large.

Every mushroom:
  * local +Z (stem->cap axis) -> radial outward at its socket (plugs in,
    points outward),
  * local +Y (the "top" apex) -> in-plane, pointing away from the pentagon
    centre (for the centre mushroom: toward the top corner).
"""

from pathlib import Path

import numpy as np
import geometry
from make_scad import _unit, _matrix, _fmt_matrix

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"

SOCKET_H = 10.0   # must match lamp_frame.scad

# stem lengths (mm) -- must match the mushroom size files
SMALL, MEDIUM, LARGE, XL = 70.0, 84.0, 100.8, 120.96
# clockwise from the top corner
CORNER_SEQUENCE = [SMALL, MEDIUM, LARGE, MEDIUM, LARGE]


def _place(v_radial_pt, top_dir, stem_len, r_floor):
    """4x4 placing a mushroom: +Z radial outward at the socket, +Y = top_dir
    (projected into the tangent plane), stem tip seated at the bore floor."""
    n = _unit(v_radial_pt)                        # radial outward -> mushroom +Z
    yc = _unit(top_dir - (top_dir @ n) * n)       # "top" apex, in tangent plane
    xc = _unit(np.cross(yc, n))                   # right-handed (x = y cross z)
    T = n * (r_floor + stem_len)                  # seat stem tip at bore floor
    return _matrix(xc, yc, n, T)


def main(diameter=200.0):
    V, F, E = geometry.build()
    radius = diameter / 2.0
    V = V * radius

    r_floor = radius - SOCKET_H / 2.0 + 1.0       # bore floor (where the tip seats)

    pentagons = [f for f in F if len(f) == 5]
    pent = max(pentagons, key=lambda f: V[f].mean(axis=0)[2])   # pick a top one
    corners = V[pent]
    centre = corners.mean(axis=0)
    n_c = _unit(centre)                           # pentagon outward axis

    # order the 5 corners CLOCKWISE (as seen from outside) starting at the top
    # corner. With n_c pointing toward an outside viewer, increasing atan2 angle
    # is counter-clockwise, so clockwise = descending angle.
    start = max(range(5), key=lambda k: corners[k][2])     # highest-z corner
    t0 = _unit((corners[start] - centre) - ((corners[start] - centre) @ n_c) * n_c)
    b = np.cross(n_c, t0)
    def cw_key(k):
        d = (corners[k] - centre)
        d = d - (d @ n_c) * n_c
        ang = np.degrees(np.arctan2(d @ b, d @ t0))
        return (-ang) % 360.0                     # 0 at start, increasing clockwise
    order = sorted(range(5), key=cw_key)

    mats, labels = [], []
    # centre: XL, top points toward the top corner
    mats.append(_place(centre, corners[start] - centre, XL, r_floor))
    labels.append(("centre", XL))
    # corners, clockwise from the top
    for seq_i, k in enumerate(order):
        v = corners[k]
        sl = CORNER_SEQUENCE[seq_i]
        mats.append(_place(v, v - centre, sl, r_floor))   # top -> away from centre
        labels.append((f"corner {seq_i} (cw)", sl))

    block = ",\n    ".join(
        "[%s, %s]" % (_fmt_matrix(m), f"{sl:.2f}")
        for (m, (_, sl)) in zip(mats, labels)
    )

    scad = f"""// Ssymmank assembly -- frame + mushrooms on one pentagon.
// Auto-generated by make_assembly.py.
//   centre socket: XL mushroom.
//   corners, clockwise from the top: small, medium, large, medium, large.
// Each mushroom's TOP points radially outward from the pentagon centre; the
// stem plugs into the outward-pointing socket.

use <mushroom_simple.scad>;
include <lamp_frame.scad>;

// each entry: [ 4x4 placement, stem_length ]
MUSH = [
    {block}
];

for (e = MUSH) multmatrix(e[0]) mushroom(e[1]);
"""
    out = MODELS / "assembly_pentagon.scad"
    out.write_text(scad)
    seq = " ".join(f"{sl:.0f}" for _, sl in labels[1:])
    print(f"saved {out}  (centre XL {XL:.0f}mm; corners cw: {seq})")


if __name__ == "__main__":
    main()
