"""
Emit an OpenSCAD model of the lamp frame (vertices + edges) with the
rhombicosidodecahedron coordinates baked in.

    lamp_frame.scad   - open in OpenSCAD and hit F5 (preview) / F6 (render)

Struts = edges (rounded cylinders), nodes = spheres at the 60 vertices.
Geometry is parametric on DIAMETER / strut & node sizes at the top of the file.
"""

from pathlib import Path

import numpy as np
import geometry

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"


def fmt_vec(v):
    return "[%.4f, %.4f, %.4f]" % (v[0], v[1], v[2])


def main(diameter=200.0):
    V, F, E = geometry.build()           # unit circumsphere
    V = V * (diameter / 2.0)             # scale to requested diameter (mm)
    stars = geometry.pentagon_stars(V, F)   # (center, [5 corner indices]) x12

    verts = ",\n    ".join(fmt_vec(v) for v in V)
    edges = ",\n    ".join("[%d, %d]" % (i, j) for i, j in E)
    star_centers = ",\n    ".join(fmt_vec(c) for c, _ in stars)
    # spokes as [star_index, vertex_index] pairs
    spokes = ",\n    ".join(
        "[%d, %d]" % (si, vi)
        for si, (_, corners) in enumerate(stars)
        for vi in corners
    )

    scad = f"""// Ssymmank lamp frame -- rhombicosidodecahedron (vertices + edges)
// 60 vertices, 120 edges, 62 faces (12 pentagons, 30 squares, 20 triangles).
// Auto-generated by make_scad.py -- edit parameters below, then F5/F6.

DIAMETER   = {diameter:.1f};   // overall lamp diameter (mm)
STRUT_R    = 1.6;     // strut (edge) radius (mm)
NODE_R     = 3.2;     // node (vertex) sphere radius (mm)
SPOKE_R    = 1.2;     // pentagon star spoke radius (mm)
STAR_R     = 3.6;     // pentagon star centre hub radius (mm)
$fn        = 24;      // smoothness

VERTS = [
    {verts}
];

EDGES = [
    {edges}
];

// one star hub at the centre of each of the 12 pentagons
STAR_CENTERS = [
    {star_centers}
];

// [star_index, vertex_index] -- 5 spokes per star, 60 total
SPOKES = [
    {spokes}
];

module bar(a, b, r) {{
    // rounded bar between two points via hull of two spheres
    hull() {{
        translate(a) sphere(r = r);
        translate(b) sphere(r = r);
    }}
}}

module frame() {{
    color("WhiteSmoke") {{
        // pentagon / square / triangle edges
        for (e = EDGES) bar(VERTS[e[0]], VERTS[e[1]], STRUT_R);
        for (v = VERTS) translate(v) sphere(r = NODE_R);
        // star hub + 5 spokes inside each pentagon
        for (s = SPOKES) bar(STAR_CENTERS[s[0]], VERTS[s[1]], SPOKE_R);
        for (c = STAR_CENTERS) translate(c) sphere(r = STAR_R);
    }}
}}

frame();
"""
    out = MODELS / "lamp_frame.scad"
    out.write_text(scad)
    print(f"saved {out}  ({len(V)} vertices, {len(E)} edges, diameter {diameter:.0f}mm)")


if __name__ == "__main__":
    main()
