"""
Emit the printable STAR TILE and a 12-tile fit-check view.

    models/star.scad             one pentagon star, print-oriented (hub up, flat)
    models/stars_assembly.scad   all 12 stars in place + the 60 connector bars

Decomposition of the frame for 3D printing
------------------------------------------
In the rhombicosidodecahedron every vertex belongs to exactly ONE pentagon, and
the 120 edges split cleanly:
  * 60 pentagon-boundary edges  -> internal to a pentagon
  * 60 inter-pentagon edges     -> the ONLY links between pentagons

So the frame is two part types:
  * STAR TILE  x12 (all congruent): 1 hub socket + 5 spokes + 5 corner sockets
                                    + 5 boundary bars  (a rigid pentagonal wheel)
  * CONNECTOR  x60 (all identical): joins a corner of one star to a corner of a
                                    neighbouring star (a triangle/square edge)

This module bakes one canonical star (hub at the origin, outward normal = +Z) so
a single printed part serves all 12 positions, plus world-space placements for
the fit-check render.
"""

from pathlib import Path

import numpy as np
import geometry
from make_scad import _unit, _matrix, _fmt_matrix, bar_transforms, node_transforms

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"


def star_frame(hub, corners):
    """World->local 4x4 for a pentagon: hub at origin, +Z = outward normal,
    +X toward the top (highest-z) corner. Returns (W2L, L2W)."""
    z = _unit(hub)
    top = max(range(5), key=lambda k: corners[k][2])
    d = corners[top] - hub
    x = _unit(d - (d @ z) * z)
    y = np.cross(z, x)
    L2W = _matrix(x, y, z, hub)                 # local -> world
    R = np.eye(4)
    R[:3, :3] = np.array([x, y, z])             # rows = basis -> world->local rot
    R[:3, 3] = -R[:3, :3] @ hub
    return R, L2W                               # W2L, L2W


def canonical_star(hub, corners):
    """Local-space node + bar transforms for one star (reusable for all 12)."""
    W2L, _ = star_frame(hub, corners)
    radius = float(np.linalg.norm(hub))

    nodes = [hub] + [corners[k] for k in range(5)]            # hub + 5 corners
    spokes = [(hub, corners[k]) for k in range(5)]            # 5 spokes
    boundary = [(corners[k], corners[(k + 1) % 5]) for k in range(5)]  # 5 edges

    node_w = node_transforms(nodes)
    bar_w = bar_transforms(spokes + boundary, radius)

    node_l = [W2L @ m for m in node_w]
    bar_l = [W2L @ m for m in bar_w]
    return node_l, bar_l


def main(diameter=200.0):
    V, F, E = geometry.build()
    radius = diameter / 2.0
    V = V * radius

    stars = geometry.pentagon_stars(V, F, bulge=1.0)          # [(centre, [idx*5])]
    pents = [(c, [V[i] for i in corners]) for c, corners in stars]

    # ---- canonical (print) star, from pentagon 0 --------------------------
    hub0, corners0 = pents[0]
    corners0 = np.array(corners0)
    node_l, bar_l = canonical_star(hub0, corners0)

    # ---- 12 placements (local -> world) for the fit-check render ----------
    placements = [star_frame(c, np.array(cs))[1] for c, cs in pents]

    # ---- the 60 connector (inter-pentagon) edges, world space -------------
    pent_sets = [set(f) for f in F if len(f) == 5]
    inter = [(a, b) for (a, b) in E
             if not any(a in s and b in s for s in pent_sets)]
    conn_w = bar_transforms([(V[a], V[b]) for a, b in inter], radius)

    node_block = ",\n        ".join(_fmt_matrix(m) for m in node_l)
    bar_block = ",\n        ".join(_fmt_matrix(m) for m in bar_l)
    place_block = ",\n    ".join(_fmt_matrix(m) for m in placements)
    conn_block = ",\n    ".join(_fmt_matrix(m) for m in conn_w)

    common = f"""DIAMETER = {diameter:.1f};

EDGE_H = 10; EDGE_T = 2;            // bar height (radial) x thickness (tangential)
STEM_TIP_R = 4; FIT_CLR = 0.35; SOCKET_WALL = 2.2;
SOCKET_H = EDGE_H; SOCKET_DEPTH = SOCKET_H - 1;
$fn = 32;
BORE_R_TIP = STEM_TIP_R + FIT_CLR;
BORE_R_MOUTH = STEM_TIP_R + FIT_CLR + 1.0;
NODE_R = BORE_R_MOUTH + SOCKET_WALL;

module edge_bar() cube([1, EDGE_T, EDGE_H], center = true);   // x scaled by matrix
module node() {{
    translate([0, 0, -SOCKET_H / 2])
    difference() {{
        cylinder(h = SOCKET_H, r = NODE_R);
        translate([0, 0, SOCKET_H - SOCKET_DEPTH + 0.5])
            cylinder(h = SOCKET_DEPTH, r1 = BORE_R_TIP, r2 = BORE_R_MOUTH);
    }}
}}"""

    # ---- star.scad : one printable tile -----------------------------------
    star_scad = f"""// Ssymmank lamp -- STAR TILE (one of 12, all congruent).
// Hub socket + 5 spokes + 5 corner sockets + 5 boundary bars, fused as one
// printable pentagonal wheel.  Hub at origin, outward normal = +Z.
// Auto-generated by make_star.py.

{common}

STAR_NODE_M = [
        {node_block}
];
STAR_BAR_M = [
        {bar_block}
];

module star() {{
    union() {{
        for (m = STAR_BAR_M)  multmatrix(m) edge_bar();
        for (m = STAR_NODE_M) multmatrix(m) node();
    }}
}}

// Print orientation: hub normal points +Z (sockets up). The dome is shallow
// (~22 deg corner angle); flip to PRINT_DOME_DOWN to rest corners on the bed.
PRINT_DOME_DOWN = false;
if (PRINT_DOME_DOWN) rotate([180, 0, 0]) star();
else star();
"""
    (MODELS / "star.scad").write_text(star_scad)

    # ---- stars_assembly.scad : 12 tiles + 60 connectors -------------------
    PALETTE = ["#4F86C6", "#C64F4F", "#4FC686", "#C6A14F", "#864FC6", "#4FC6C6",
               "#C64F86", "#86C64F", "#C6864F", "#4F4FC6", "#C6C64F", "#9C9C9C"]
    color_lines = "\n".join(
        f'    color("{PALETTE[i]}") multmatrix(PLACE_M[{i}]) star();'
        for i in range(12))

    asm_scad = f"""// Ssymmank lamp -- FIT CHECK: 12 star tiles in place + 60 connector bars.
// Each coloured pentagonal wheel is one printed STAR TILE; the grey bars are
// the 60 identical CONNECTOR parts that link neighbouring stars.
// Auto-generated by make_star.py.

{common}

STAR_NODE_M = [
        {node_block}
];
STAR_BAR_M = [
        {bar_block}
];
module star() {{
    union() {{
        for (m = STAR_BAR_M)  multmatrix(m) edge_bar();
        for (m = STAR_NODE_M) multmatrix(m) node();
    }}
}}

PLACE_M = [
    {place_block}
];
CONN_M = [
    {conn_block}
];

{color_lines}
color("#9C9C9C") for (m = CONN_M) multmatrix(m) edge_bar();
"""
    (MODELS / "stars_assembly.scad").write_text(asm_scad)

    print(f"saved models/star.scad  (1 tile: {len(node_l)} sockets, {len(bar_l)} bars)")
    print(f"saved models/stars_assembly.scad  (12 tiles + {len(conn_w)} connectors)")


if __name__ == "__main__":
    main()
