"""
Emit an OpenSCAD model of the lamp frame, rhombicosidodecahedron coordinates
baked in.

    models/lamp_frame.scad   - open in OpenSCAD and hit F5 (preview) / F6 (render)

The frame is:
  * 60 cylindrical VERTEX SOCKETS, one per vertex, each pointing radially
    outward. A mushroom stem (base radius STEM_TIP_R) plugs into the bore, so
    every mushroom points outward from the sphere.
  * 120 flat EDGE BARS (2 mm thick x 10 mm wide) along the edges, the flat face
    lying tangent to the sphere.

All orientation maths is done here in numpy and baked into the .scad as 4x4
multmatrix transforms, so the .scad itself is just data + two tiny modules.
"""

from pathlib import Path

import numpy as np
import geometry

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"


def _unit(v):
    return v / np.linalg.norm(v)


def _matrix(col0, col1, col2, translate):
    """Row-major 4x4 mapping local x,y,z axes onto col0,col1,col2 (+translate)."""
    m = np.eye(4)
    m[:3, 0] = col0
    m[:3, 1] = col1
    m[:3, 2] = col2
    m[:3, 3] = translate
    return m


def _fmt_matrix(m):
    return "[" + ", ".join("[%.5f, %.5f, %.5f, %.5f]" % tuple(row) for row in m) + "]"


def edge_transforms(V, E, radius):
    """One transform per edge: x-axis along the edge, z-axis radial, y-axis
    tangential. The bar stands as a radial fin (its tall side along z), centred
    on the sphere at `radius` so it runs the full height of the sockets."""
    mats, lengths = [], []
    for i, j in E:
        a, b = V[i], V[j]
        d = b - a
        L = float(np.linalg.norm(d))
        e = d / L
        mid = (a + b) / 2.0
        radial = _unit(mid)                 # outward at the edge midpoint
        tang = _unit(np.cross(radial, e))   # tangential, perpendicular to edge
        z = _unit(np.cross(e, tang))        # radial -> the bar's tall (height) axis
        centre = radial * radius            # sit on the sphere, level with sockets
        mats.append(_matrix(e, tang, z, centre))
        lengths.append(L)
    return mats, float(np.mean(lengths))    # all edges equal on an Archimedean solid


def node_transforms(V):
    """One transform per vertex: z-axis points radially outward (socket axis)."""
    mats = []
    for v in V:
        n = _unit(v)
        ref = np.array([0.0, 0.0, 1.0])
        if abs(float(n @ ref)) > 0.9:
            ref = np.array([1.0, 0.0, 0.0])
        u = _unit(np.cross(n, ref))
        w = np.cross(n, u)
        mats.append(_matrix(u, w, n, v))
    return mats


def main(diameter=200.0):
    V, F, E = geometry.build()           # unit circumsphere
    radius = diameter / 2.0
    V = V * radius                       # scale to requested diameter (mm)

    edge_mats, edge_len = edge_transforms(V, E, radius)
    node_mats = node_transforms(V)

    edge_block = ",\n    ".join(_fmt_matrix(m) for m in edge_mats)
    node_block = ",\n    ".join(_fmt_matrix(m) for m in node_mats)

    scad = f"""// Ssymmank lamp frame -- rhombicosidodecahedron
// 60 vertex sockets + 120 flat edge bars.  Auto-generated by make_scad.py.
// Each socket points radially outward and accepts one mushroom stem.

DIAMETER  = {diameter:.1f};   // overall lamp diameter (mm)

// ---- edge bars (flat fins standing radially) ------------------------------
EDGE_L    = {edge_len:.4f};   // edge (chord) length (mm) -- equal for all edges
EDGE_H    = 10;       // bar HEIGHT (mm) -- radial; runs the height of the sockets
EDGE_T    = 2;        // bar thickness (mm) -- tangential

// ---- vertex sockets -------------------------------------------------------
STEM_TIP_R = 4;       // mushroom stem base radius (must match the mushroom)
FIT_CLR    = 0.35;    // radial clearance so the stem slides in
SOCKET_WALL  = 2.2;   // wall around the bore (mm)
SOCKET_H   = EDGE_H;  // socket height = edge height, so edges run its full height
SOCKET_DEPTH = SOCKET_H - 1;   // bore depth (1 mm floor at the inner end)

$fn = 32;

BORE_R_TIP  = STEM_TIP_R + FIT_CLR;        // bore radius at the deep (tip) end
BORE_R_MOUTH = STEM_TIP_R + FIT_CLR + 1.0; // slightly wider at the outer mouth
NODE_R = BORE_R_MOUTH + SOCKET_WALL;       // hub outer radius

EDGE_M = [
    {edge_block}
];

NODE_M = [
    {node_block}
];

module edge_bar() cube([EDGE_L, EDGE_T, EDGE_H], center = true);

// Cylindrical socket on the +Z (outward) axis, centred on the vertex so it
// spans the same radial band as the edge fins. Conical bore (matched to the
// tapered mushroom stem) opens at the outer face; a mushroom plugs in pointing
// outward.
module node() {{
    translate([0, 0, -SOCKET_H / 2])
    difference() {{
        cylinder(h = SOCKET_H, r = NODE_R);
        translate([0, 0, SOCKET_H - SOCKET_DEPTH + 0.5])
            cylinder(h = SOCKET_DEPTH, r1 = BORE_R_TIP, r2 = BORE_R_MOUTH);
    }}
}}

color("WhiteSmoke") {{
    for (m = EDGE_M) multmatrix(m) edge_bar();
    for (m = NODE_M) multmatrix(m) node();
}}
"""
    out = MODELS / "lamp_frame.scad"
    out.write_text(scad)
    print(f"saved {out}  ({len(V)} vertices, {len(E)} edges, "
          f"edge length {edge_len:.1f}mm, diameter {diameter:.0f}mm)")


if __name__ == "__main__":
    main()
