"""
Emit the full OpenSCAD assembly: the frame with mushrooms on every pentagon.

    models/assembly.scad

The same per-pentagon pattern is applied to all 12 pentagons:
  * the pentagon-CENTRE socket gets an XL mushroom,
  * the 5 corner sockets get, CLOCKWISE from the top corner (as seen from
    outside the lamp): small, medium, large, medium, large.

In a rhombicosidodecahedron each vertex belongs to exactly one pentagon, so the
12 x 5 = 60 corners cover all 60 vertex sockets once, and the 12 centres cover
the 12 hub sockets -> 72 mushrooms, one per socket.

Every mushroom:
  * local +Z (stem->cap axis) -> radial outward at its socket (plugs in,
    points outward),
  * local +Y (the "top" apex) -> in-plane, pointing away from the pentagon
    centre (for the centre mushroom: toward that pentagon's top corner).
"""

from pathlib import Path

import numpy as np
import geometry
from make_scad import _unit, _matrix, _fmt_matrix

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"

SOCKET_H = 10.0   # must match lamp_frame.scad

# stem lengths (mm) -- must match the mushroom size files
SMALL, MEDIUM, LARGE, XL = 70.0, 84.0, 100.8, 120.96
# clockwise from the top corner
CORNER_SEQUENCE = [SMALL, MEDIUM, LARGE, MEDIUM, LARGE]


def _place(socket_pt, top_dir, stem_len, r_floor):
    """4x4 placing a mushroom: +Z radial outward at the socket, +Y = top_dir
    (projected into the tangent plane), stem tip seated at the bore floor."""
    n = _unit(socket_pt)                          # radial outward -> mushroom +Z
    yc = _unit(top_dir - (top_dir @ n) * n)       # "top" apex, in tangent plane
    xc = _unit(np.cross(yc, n))                   # right-handed (x = y cross z)
    T = n * (r_floor + stem_len)                  # seat stem tip at bore floor
    return _matrix(xc, yc, n, T)


def pentagon_placements(corners, r_floor):
    """All 6 placements for one pentagon: centre (XL) + 5 corners (s/m/l/m/l
    clockwise from the top corner)."""
    centre = corners.mean(axis=0)
    n_c = _unit(centre)

    # clockwise order (as seen from outside) starting at the top (highest-z) corner
    start = max(range(5), key=lambda k: corners[k][2])
    d0 = corners[start] - centre
    t0 = _unit(d0 - (d0 @ n_c) * n_c)
    b = np.cross(n_c, t0)
    def cw_key(k):
        d = corners[k] - centre
        d = d - (d @ n_c) * n_c
        ang = np.degrees(np.arctan2(d @ b, d @ t0))
        return (-ang) % 360.0                     # 0 at start, increasing clockwise
    order = sorted(range(5), key=cw_key)

    out = [(_place(centre, corners[start] - centre, XL, r_floor), XL)]   # centre
    for seq_i, k in enumerate(order):
        v = corners[k]
        out.append((_place(v, v - centre, CORNER_SEQUENCE[seq_i], r_floor),
                    CORNER_SEQUENCE[seq_i]))
    return out


def main(diameter=200.0):
    V, F, E = geometry.build()
    radius = diameter / 2.0
    V = V * radius
    r_floor = radius - SOCKET_H / 2.0 + 1.0       # bore floor (where the tip seats)

    placements = []
    for f in F:
        if len(f) == 5:
            placements += pentagon_placements(V[f], r_floor)

    block = ",\n    ".join(
        "[%s, %.2f]" % (_fmt_matrix(m), sl) for m, sl in placements
    )

    scad = f"""// Ssymmank assembly -- full frame + mushrooms on all 12 pentagons.
// Auto-generated by make_assembly.py.
// Per pentagon: centre socket = XL; corners clockwise from the top =
// small, medium, large, medium, large.  72 mushrooms, one per socket.
// Each mushroom's TOP points radially outward from its pentagon centre.

use <mushroom_simple.scad>;
include <lamp_frame.scad>;

// each entry: [ 4x4 placement, stem_length ]
MUSH = [
    {block}
];

for (e = MUSH) multmatrix(e[0]) mushroom(e[1]);
"""
    out = MODELS / "assembly.scad"
    out.write_text(scad)
    print(f"saved {out}  ({len(placements)} mushrooms across "
          f"{sum(1 for f in F if len(f) == 5)} pentagons)")


if __name__ == "__main__":
    main()
