"""
Emit an OpenSCAD assembly: the frame plus five mushrooms on the five corners of
one pentagon, each oriented so its TOP (the pentagon apex, +Y in the mushroom's
local frame) points radially OUTWARD relative to that frame pentagon's centre.

    models/assembly_pentagon.scad

Each mushroom:
  * local +Z (stem->cap axis) -> radial outward at its vertex (so it plugs into
    the socket and points outward),
  * local +Y (the "top" apex) -> the in-plane direction away from the pentagon
    centre.
"""

from pathlib import Path

import numpy as np
import geometry
from make_scad import _unit, _matrix, _fmt_matrix

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"

SOCKET_H = 10.0   # must match lamp_frame.scad


def main(diameter=200.0, stem_len=70.0):
    V, F, E = geometry.build()
    radius = diameter / 2.0
    V = V * radius

    r_floor = radius - SOCKET_H / 2.0 + 1.0      # bore floor (where the tip seats)

    pentagons = [f for f in F if len(f) == 5]
    pent = max(pentagons, key=lambda f: V[f].mean(axis=0)[2])   # pick a top one
    centre = V[pent].mean(axis=0)

    mats = []
    for idx in pent:
        v = V[idx]
        n = _unit(v)                              # radial outward -> mushroom +Z
        d = v - centre
        apex = _unit(d - (d @ n) * n)             # outward, in the tangent plane
        zc = n
        yc = apex                                 # mushroom "top" -> outward
        xc = _unit(np.cross(yc, zc))              # right-handed (x = y cross z)
        # seat the stem tip (local 0,0,-stem_len) at the bore floor along n
        T = n * (r_floor + stem_len)
        mats.append(_matrix(xc, yc, zc, T))

    block = ",\n    ".join(_fmt_matrix(m) for m in mats)

    scad = f"""// Ssymmank assembly -- frame + 5 mushrooms on one pentagon.
// Auto-generated by make_assembly.py.
// Every mushroom's TOP (pentagon apex) points radially outward from the
// pentagon centre; its stem plugs into the vertex socket pointing outward.

use <mushroom_simple.scad>;
include <lamp_frame.scad>;

STEM_LEN_DEMO = {stem_len:.1f};

// one 4x4 placement per pentagon corner
MUSH_M = [
    {block}
];

for (m = MUSH_M) multmatrix(m) mushroom(STEM_LEN_DEMO);
"""
    out = MODELS / "assembly_pentagon.scad"
    out.write_text(scad)
    print(f"saved {out}  (5 mushrooms, stem {stem_len:.0f}mm, on a pentagon)")


if __name__ == "__main__":
    main()
