"""
Emit an OpenSCAD model of the lamp frame as ONE monolithic piece, with
rhombicosidodecahedron coordinates baked in.

    models/frame/lamp_frame.scad   - open in OpenSCAD and hit F5 / F6

The frame is:
  * 60 cylindrical VERTEX SOCKETS, one per vertex, each pointing radially
    outward. A mushroom stem (base radius STEM_TIP_R) plugs into the bore, so
    every mushroom points outward from the sphere.
  * 120 flat EDGE BARS (2 mm thick x 10 mm wide) along the edges, the flat face
    lying tangent to the sphere.

This is the reference whole-frame model.  The PRINTABLE decomposition (the frame
split into 12 star tiles + 60 connectors) is generated by build_star.py.

Run:  uv run python src/frame/build_frame.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))   # src/ -> import core

from core import geometry
from core.transforms import _fmt_matrix, bar_transforms, node_transforms

MODELS = Path(__file__).resolve().parents[2] / "models" / "frame"


def main(diameter=200.0):
    V, F, E = geometry.build()           # unit circumsphere
    radius = diameter / 2.0
    V = V * radius                       # scale to requested diameter (mm)

    # 12 extra sockets at the pentagon centres (projected out onto the sphere),
    # each joined to its 5 corners by a spoke -> 72 sockets, 180 bars total.
    stars = geometry.pentagon_stars(V, F, bulge=1.0)
    centres = [c for c, _ in stars]

    edge_pairs  = [(V[i], V[j]) for i, j in E]
    spoke_pairs = [(c, V[ci]) for c, corners in stars for ci in corners]

    bar_mats  = bar_transforms(edge_pairs + spoke_pairs, radius)
    node_mats = node_transforms(list(V) + centres)

    # node TYPE: the solid is vertex-transitive, so the 60 polyhedron vertices
    # are all one type ("V"); the 12 pentagon centres are the other ("H" hub).
    node_type = [0] * len(V) + [1] * len(centres)   # 0 = vertex, 1 = hub

    bar_block  = ",\n    ".join(_fmt_matrix(m) for m in bar_mats)
    node_block = ",\n    ".join(_fmt_matrix(m) for m in node_mats)
    type_block = ", ".join(str(t) for t in node_type)

    scad = f"""// Ssymmank lamp frame -- rhombicosidodecahedron
// 72 vertex sockets (60 polyhedron vertices + 12 pentagon centres) and
// 180 flat edge bars (120 polyhedron edges + 60 pentagon spokes).
// Auto-generated by build_frame.py.  Each socket points radially outward and
// accepts one mushroom stem.

DIAMETER  = {diameter:.1f};   // overall lamp diameter (mm)

// ---- edge bars (flat fins standing radially) ------------------------------
EDGE_H    = 10;       // bar HEIGHT (mm) -- radial; runs the height of the sockets
EDGE_T    = 2;        // bar thickness (mm) -- tangential
                      // (bar length is baked into each transform)

// ---- vertex sockets -------------------------------------------------------
STEM_TIP_R = 4;       // mushroom stem base radius (must match the mushroom)
FIT_CLR    = 0.35;    // radial clearance so the stem slides in
SOCKET_WALL  = 2.2;   // wall around the bore (mm)
SOCKET_H   = EDGE_H;  // socket height = edge height, so edges run its full height
SOCKET_DEPTH = SOCKET_H - 1;   // bore depth (1 mm floor at the inner end)

$fn = 32;

BORE_R_TIP  = STEM_TIP_R + FIT_CLR;        // bore radius at the deep (tip) end
BORE_R_MOUTH = STEM_TIP_R + FIT_CLR + 1.0; // slightly wider at the outer mouth
NODE_R = BORE_R_MOUTH + SOCKET_WALL;       // hub outer radius

// each bar's transform; its x column length IS the bar length
BAR_M = [
    {bar_block}
];

NODE_M = [
    {node_block}
];

// ---- node categories ------------------------------------------------------
// The rhombicosidodecahedron is vertex-transitive, so there are just two node
// types.  NODE_TYPE[i] indexes into TYPE_NAME / TYPE_COLOR.
//   0  "V" vertex node  -- 60, a 3.4.5.4 polyhedron vertex (4 edges + 1 spoke)
//   1  "H" hub node     -- 12, a pentagon centre (5 spokes)
TYPE_NAME  = ["V", "H"];
TYPE_COLOR = ["SteelBlue", "Crimson"];
NODE_TYPE  = [{type_block}];
COLOR_NODES_BY_TYPE = true;   // set false for a single colour

module edge_bar() cube([1, EDGE_T, EDGE_H], center = true);  // x scaled by BAR_M

// Cylindrical socket on the +Z (outward) axis, centred on the vertex so it
// spans the same radial band as the edge fins. Conical bore (matched to the
// tapered mushroom stem) opens at the outer face; a mushroom plugs in pointing
// outward.
module node() {{
    translate([0, 0, -SOCKET_H / 2])
    difference() {{
        cylinder(h = SOCKET_H, r = NODE_R);
        translate([0, 0, SOCKET_H - SOCKET_DEPTH + 0.5])
            cylinder(h = SOCKET_DEPTH, r1 = BORE_R_TIP, r2 = BORE_R_MOUTH);
    }}
}}

// bars stay neutral; nodes are coloured by type
color("WhiteSmoke") for (m = BAR_M) multmatrix(m) edge_bar();

for (i = [0 : len(NODE_M) - 1])
    color(COLOR_NODES_BY_TYPE ? TYPE_COLOR[NODE_TYPE[i]] : "WhiteSmoke")
        multmatrix(NODE_M[i]) node();
"""
    out = MODELS / "lamp_frame.scad"
    out.write_text(scad)
    print(f"saved {out}  ({len(node_mats)} sockets, {len(bar_mats)} bars, "
          f"diameter {diameter:.0f}mm)")


if __name__ == "__main__":
    main()
